package Auditoriski3.Zadacha1;

import java.util.Arrays;

public class Bank {
    private Account[] accounts;
    private int totalAccounts;
    private int maxAccounts; //size of accounts

    public Bank(int maxAccounts) {
        this.maxAccounts = maxAccounts;
        this.accounts = new Account[maxAccounts];
        this.totalAccounts = 0;
    }

    public void addAccount(Account account) {
        if (totalAccounts == maxAccounts) {
            //move reference of accounts[] to a new one generated by Arrays
            accounts = Arrays.copyOf(accounts, maxAccounts * 2);
        }
        accounts[totalAccounts++] = account;
    }

    public double totalAssets() {
        double total = 0;
        for (Account account : accounts) {
            total += account.getCurrentAmount();
        }
        return total;
    }

    public void addInterestToAllAccounts() {
        for (Account account : accounts) {
            //instanceOF ili getClass
            // instanceof - da e objekt od A ili nejzini deca
            // dali getclass - koja e klasata
            //Polosh nacin ->
//            if (account instanceof InterestBearingAccount) {
//                //objekt od interface ne postoi, konstrukt od dete klasa ili anonimna
//                InterestBearingAccount interestBearingAccount = (InterestBearingAccount) account;
//                interestBearingAccount.addInterest();
//            }
            //Podobar nacin
            if(account.getAccountType().equals(AccountType.INTEREST)) { //dali imame account od tip interest
                //uste nemozeme da pristapime do .addInterest, go nema vo account
                //no site accounti od tip IntBearAcc imaat add interest
                InterestBearingAccount interestBearingAccount = (InterestBearingAccount) account;
                interestBearingAccount.addInterest();
            }

        }
    }
}
